<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function inside_iframe_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::request()->get('display') === 'iframe') {
    array_unshift($suggestions, 'page__iframe');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - node: The node object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function inside_iframe_preprocess_html(&$variables) {
  if (\Drupal::request()->get('display') === 'iframe') {
    // We don't need the toolbar within the iframe.
    unset($variables['page_top']['toolbar']);
  }
}

/**
 * Implements hook_page_attachments().
 */
function inside_iframe_page_attachments(&$page) {
  $page['#cache']['contexts'][] = 'url.query_args:display';
}

/**
 * Implements hook_page_attachments_alter().
 */
function inside_iframe_page_attachments_alter(array &$attachments) {
  if (\Drupal::request()->get('display') === 'iframe') {
    // Conditionally remove an asset.
    if (in_array('eu_cookie_compliance/eu_cookie_compliance', $attachments['#attached']['library'])) {
      $index = array_search('eu_cookie_compliance/eu_cookie_compliance', $attachments['#attached']['library']);
      unset($attachments['#attached']['library'][$index]);
    }
  }
}
