<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function inside_iframe_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (\Drupal::request()->get('display') === 'iframe') {
    array_unshift($suggestions, 'page__iframe');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - node: The node object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function inside_iframe_preprocess_html(&$variables) {
  if (\Drupal::request()->get('display') === 'iframe') {
    // We don't need the toolbar within the iframe.
    unset($variables['page_top']['toolbar']);
  }
}

///**
// * Implements hook_preprocess_HOOK().
// *
// * @param array $variables
// *   An associative array containing:
// *   - elements: An array of elements to display in view mode.
// *   - node: The node object.
// *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
// */
//function inside_iframe_preprocess_page(&$variables) {
//  if (\Drupal::request()->get('display') === 'iframe') {
//
//  }
//}
