<?php
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function oiko_timeline_theme($existing, $type, $theme, $path) {
  return array(
    'comparative_timeline' => array(
      'variables' => array(
      ),
    ),
  );
}


/**
 * Implements hook_preprocess_comparative_timeline().
 */
function oiko_timeline_preprocess_comparative_timeline(&$variables, $hook) {
  $variables['sidebar'] = [
    '#theme' => 'sidebar',
  ];

  $cidoc_entity_query = \Drupal::service('entity.query')
    ->get('cidoc_entity')
    ->condition('timeline_preselect_option', TRUE)
    ->condition('status', TRUE);

  $place_ids = $cidoc_entity_query->execute();
  $ids = $place_ids;
  $loaded = \Drupal::service('entity_type.manager')->getStorage('cidoc_entity')->loadMultiple($ids);
  $links = [];

  foreach ($loaded as $entity) {
    $links[Url::fromRoute('oiko_timeline.comparision_data', ['cidoc_entity' => $entity->id()])->toString()] = $entity->label();
  }

  // Work out what items to show in the initial select.
  $variables['js'] = [
    '#attached' => array(
      'library' =>  array(
        'oiko_timeline/comparative_timeline'
      ),
      'drupalSettings' => [
        'oiko_timeline' => [
          'defaultOptions' => $links,
        ],
      ],
    ),
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function oiko_timeline_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  return \Drupal::service('oiko_timeline.hook_implementations')->entity_base_field_info($entity_type);
}
