<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;

/**
* Implements hook_field_group_pre_render().
*
* @param Array $element
*   Group being rendered.
* @param Object $group
*   The Field group info.
* @param $rendering_object
*   The entity / form being rendered
*/
function oiko_prototype_field_group_pre_render(&$element, &$group, &$rendering_object) {
  if ($rendering_object['#entity_type'] == 'cidoc_entity') {
    if (isset($element['#attributes']) && is_object($element['#attributes'])) {
      $element['#attributes']->addClass('cidoc-field-group');
      // Shortcut - use the group name as a class so we can do theming.
      if (!empty($group->group_name)) {
        $element['#attributes']->addClass($group->group_name);
      }
    }
  }
}
