enabled_entities:
  - e5_event
  - e6_destruction
  - e7_activity
  - e9_move
  - e12_production
  - e21_person
  - e35_title
  - e41_appellation
  - e42_identifier
  - e52_time_span
  - e53_place
  - e55_type
  - e56_language
  - e57_material
  - e65_creation
  - e66_formation
  - e67_birth
  - e68_dissolution
  - e69_death
  - e74_group
  - e85_joining
  - e86_leaving
  - ec1_work
  - ec2_genre
  - ec3_formal_feature
  - ec4_syllabic_scheme
  - ec5_rhyme_scheme
  - ec6_music
  - ec7_source
  - ec8_manuscript
  - ec9_print
  - ec10_marriage
  - ec11_melodic_scheme
enabled_properties:
  - p1_is_identified_by
  - p2_has_type
  - p4_has_time_span
  - p7_took_place_at
  - p9_consists_of
  - p10_falls_within
  - p11_had_participant
  - p12_occurred_in_the_presence_of
  - p13_destroyed
  - p14_carried_out_by
  - p26_moved_to
  - p27_moved_from
  - p45_consists_of
  - p48_has_preferred_identifier
  - p67_refers_to
  - p78_is_identified_by
  - p87_is_identified_by
  - p89_falls_within
  - p94_has_created
  - p95_has_formed
  - p96_by_mother
  - p97_from_father
  - p98_brought_into_life
  - p99_dissolved
  - p100_was_death_of
  - p102_has_title
  - p108_has_produced
  - p128_carries
  - p131_is_identified_by
  - p134_continued
  - p139_has_alternative_form
  - p143_joined
  - p144_joined_with
  - p145_separated
  - p146_separated_from
  - pa1_has_patron
  - pa2_has_acquaintance
  - pa3_has_friend
  - pa4_has_muse
  - pa5_has_lover
  - pa6_has_murder_victim
  - pa7_has_sibling
  - pa8_has_cousin
  - pa9_has_aunt_or_uncle
  - pa10_has_grandchild
  - pa11_has_ancestor
  - pa12_has_adoptive_child
  - pa13_has_illegitimate_child
  - pa14_has_relative
  - pa15_has_child-in-law
  - pa16_has_sibling-in-law
  - pa17_has_godfather
  - pa18_has_godmother
  - pa19_has_language
  - pc1_has_metrical_affinities_with
  - pc2_is_contrafactum_of
  - pc3_has_genre
  - pc4_has_formal_feature
  - pc5_has_expression
  - pc6_has_alternative_attribution
  - pc7_has_music
  - pc8_has_syllabic_scheme
  - pc9_has_rhyme_scheme
  - pc10_has_melodic_scheme
  - pc11_has_spouse
  - pc12_has_intertextual_relationship
  - pc13_has_response
  - pc14_has_indirect_source
