definitions:
  system__admin_content:
    weight: -79
    menu_name: admin
    parent: system.admin
    enabled: true
    expanded: false
  entity__cidoc_entity__collection:
    weight: -78
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_structure:
    weight: -77
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -76
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -75
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -74
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -73
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -72
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: -71
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
