mapping:
  comment_field_data:
    name: text_anonymizer
    mail: email_anonymizer
  user__user_picture:
    user_picture_alt: text_anonymizer
    user_picture_title: text_anonymizer
  users_field_data:
    name: text_anonymizer
    pass: password_anonymizer
    mail: email_anonymizer
    login: username_anonymizer
empty_tables: {  }
