url_template: 'https://api.maptiler.com/maps/95c8615b-23d0-4ab3-ac7a-7077aec69487/{z}/{x}/{y}.png?key=ds4fO3RUSOGgr8W2wsDv'
attribution: 'Powered by <a href="http://leafletjs.com/">Leaflet</a> and <a href="https://cloud.maptiler.com//">Maptyler</a>.'
color_system: entity_class
