<?php
use Drupal\Core\Url;


/**
 * Implements hook_theme().
 */
function oiko_app_theme($existing, $type, $theme, $path) {
  return array(
    'oiko_app' => array(
      'variables' => array(
      ),
    ),
    'main_cidoc_search' => array(
      'variables' => array(
        'placeholder_map' => 'Search events',
        'no_search_map' => 'Search for events, people, groups, places or objects e.g. \'The battle of Milvian Bridge\' or \'the Xiongnu\'.',
        'placeholder_timeline' => 'Search groups and people',
        'no_search_timeline' => 'Search for communities, empires or groups to compare on your timeline e.g. \'The Roman Empire\' or \'the Han\'.',
        'no_results_text' => 'No results found.',
        'searching_text' => 'Searching through known space and time...',
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_oiko_app().
 */
function oiko_app_preprocess_oiko_app(&$variables, $hook) {
  $variables['sidebar'] = [
    '#theme' => 'sidebar',
  ];

  $map = leaflet_map_get_info('Ancient Terrain');
  $map['sidebar'] = TRUE;
  $map['pagestate'] = TRUE;
  $map['timeline'] = TRUE;
  $map['search'] = TRUE;
  $map['empires'] = TRUE;
  $map['clustering'] = TRUE;
  $map['locate'] = TRUE;
  $map['settings']['layerControl'] = FALSE;
  $map['settings']['zoomControl'] = FALSE;
  $map['zoomControl'] = 'bottomright';
  $map['data-url'] = Url::fromRoute('oiko_leaflet.map_page_controller_allEntities')->toString();
  $height = 'full';

  $variables['map'] = leaflet_render_map($map, [], $height);

  $variables['timeline'] = array(
    '#theme' => 'comparative_timeline',
  );


  $variables['js'] = [
    '#attached' => array(
      'library' =>  array(
        'oiko_app/app'
      ),
    ),
  ];
}

/**
 * Implements hook_toolbar().
 */
function oiko_app_toolbar() {
  $items = [];
  $items['welcome_modal'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if (!\Drupal::currentUser()->hasPermission('reshow welcome modal')) {
    return $items;
  }

  $items['welcome_modal'] += array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'html_tag',
      '#tag' => 'button',
      '#value' => t('Welcome modal'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-system-admin-content'),
        'aria-pressed' => 'false',
      ),
    ),
    '#wrapper_attributes' => array(
      'class' => array('tour-toolbar-tab'),
      'data-open' => 'block-welcomeblock',
    ),
  );

  return $items;
}
