<?php
use Drupal\Core\Url;


/**
 * Implements hook_theme().
 */
function oiko_app_theme($existing, $type, $theme, $path) {
  return array(
    'oiko_app' => array(
      'variables' => array(
      ),
    ),
    'main_cidoc_search' => array(
      'variables' => array(
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_oiko_app().
 */
function oiko_app_preprocess_oiko_app(&$variables, $hook) {
  $variables['sidebar'] = [
    '#theme' => 'sidebar',
  ];

  $map = leaflet_map_get_info('Ancient Terrain');
  $map['sidebar'] = TRUE;
  $map['pagestate'] = TRUE;
  $map['timeline'] = TRUE;
  $map['search'] = TRUE;
  $map['empires'] = TRUE;
  $map['clustering'] = TRUE;
  $map['locate'] = TRUE;
  $map['settings']['layerControl'] = FALSE;
  $map['settings']['zoomControl'] = FALSE;
  $map['zoomControl'] = 'bottomright';
  $map['data-url'] = Url::fromRoute('oiko_leaflet.map_page_controller_allEntities')->toString();
  $height = 'full';

  $variables['map'] = leaflet_render_map($map, [], $height);

  $variables['timeline'] = array(
    '#theme' => 'comparative_timeline',
  );


  $variables['js'] = [
    '#attached' => array(
      'library' =>  array(
        'oiko_app/app'
      ),
    ),
  ];
}
