<?php


/**
 * Implements hook_theme().
 */
function oiko_app_theme($existing, $type, $theme, $path) {
  return array(
    'oiko_app' => array(
      'variables' => array(
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_oiko_app().
 */
function oiko_app_preprocess_oiko_app(&$variables, $hook) {
  $variables['sidebar'] = [
    '#theme' => 'sidebar',
  ];

  $variables['js'] = [
    '#attached' => array(
      'library' =>  array(
        'oiko_app/app'
      ),
      'drupalSettings' => [

      ],
    ),
  ];
}
